# Generated by Django 6.1.1 on 2026-10-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('channel_name', models.CharField(max_length=500)),
                ('subscriber_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='analytics.channel')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_engagement', models.BigIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('like_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('comment_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_analysis', to='analytics.video')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['channel', 'published_at'], name='analytics_v_channel_f1b897_idx'),
        ),
    ]
